version: '3'

services:
  nest-app:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL
      - NODE_ENV=production
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - JWT_KEY
    restart: always
    networks:
      - nest-network

  postgres:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - nest-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 5454
    ports:
      - "5454:5454"
    depends_on:
      - postgres
    volumes:
    - ./servers.json:/pgadmin4/servers.json

volumes:
  pgdata:


networks:
  nest-network:
    driver: bridge
