name: Deploy to server

on:
  push:
   branches:
    - main

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setting up SSH
        uses: webfactory/ssh-agent@v0.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into server and execute command
        uses: appleboy/ssh-action@v0.4.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
              cd quizapidocker/
              git pull origin main

    